name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI
        uses: informaticsmatters/trigger-ci-action@v1
        with:
          ci-owner: ${{ github.actor }}
          ci-repository: openjdk-build-android4
          ci-ref: refs/heads/jre8-gcc-libapi19-newheaders
          ci-name: Build OpenJDK 8 for Android
          ci-user: ${{ github.actor }}
          ci-user-token: ${{ secrets.USER_TOKEN }}
